# Generated by Django 2.0.6 on 2018-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0002_auto_20180604_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='role',
            field=models.IntegerField(choices=[(0, 'Administrator'), (1, 'Staff')], default=1),
        ),
    ]
