# Generated by Django 2.0.6 on 2018-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20180613_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='userimages'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(help_text='Write a description for volunteers to understand the context of your projects.', max_length=5000, verbose_name='Organization description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Type the name of your organization.', max_length=50, verbose_name='Organization name'),
        ),
    ]
