# Generated by Django 2.0.6 on 2018-06-24 01:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20180614_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='budget',
            field=models.CharField(choices=[('B000', '<$100K'), ('B001', '$100K-$500K'), ('B005', '$500K-$1MM'), ('B010', '$1MM-$5MM'), ('B050', '$5MM-$20MM'), ('B200', '$20MM-$50MM'), ('B500', '>$50MM')], default='B000', help_text='Select the budget range that fits your organization best', max_length=7, verbose_name='Yearly budget'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='main_cause',
            field=models.CharField(choices=[('ED', 'Education'), ('HE', 'Health'), ('EN', 'Environment'), ('SS', 'Social Services'), ('TR', 'Transportation'), ('EE', 'Energy and Environment'), ('ID', 'International development'), ('PS', 'Public Safety'), ('EC', 'Economic Development'), ('OT', 'Other')], default='ED', help_text='What is the main social cause that this organization has as a goal?', max_length=2, verbose_name='Main social cause'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_scope',
            field=models.CharField(choices=[('LO', 'City/Local'), ('ST', 'State'), ('RE', 'Region (i.e. Midwest, Northeast, etc.)'), ('CO', 'Country'), ('MN', 'Multi-national'), ('OT', 'Other')], default='LO', help_text='What is the geographical scope that this organization targets?', max_length=2, verbose_name='Geographical scope'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(max_length=100, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street_address',
            field=models.CharField(max_length=300, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True, help_text="Add a link to your organization's home page so volunteers can reach you", null=True, verbose_name='External website URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='years_operation',
            field=models.CharField(choices=[('Y00', 'less than 1 year'), ('Y01', '1 to 5 years'), ('Y05', '5 to 10 years'), ('Y10', '10 to 25 years'), ('Y25', '25 or more years')], default='Y00', help_text='For how long has the organization been in operation?', max_length=3, verbose_name='Years in operation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zipcode',
            field=models.CharField(max_length=20, verbose_name='ZIP/Postal code'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='organization',
            field=models.ForeignKey(help_text='Organization to which the user is applying to be member of', on_delete=django.db.models.deletion.CASCADE, to='marketplace.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='private_reviewer_notes',
            field=models.TextField(blank=True, help_text='Write any private comments regarding this decision. IMPORTANT: these notes are private to the organization, but all members of the organization will be able to see them.', max_length=5000, null=True, verbose_name='Private review notes'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='public_reviewer_comments',
            field=models.TextField(blank=True, help_text='Write any comments you have for the applicant. IMPORTANT: These comments will be public and can be viewed by users outside ot the organization.', max_length=5000, null=True, verbose_name='Public reviewer comments'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='request_date',
            field=models.DateTimeField(help_text='Date and time in which the membership request was created', verbose_name='Review date'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='resolution_date',
            field=models.DateTimeField(blank=True, help_text='Date and time in which the membership request was resolved', null=True, verbose_name='Resolution date'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='role',
            field=models.IntegerField(choices=[(0, 'Administrator'), (1, 'Staff')], default=1, help_text='Select the role of this user in the organization. IMPORTANT: Administrators will have full permissions over the organization so only assign this permission if you are sure you grant this user full control of the organization.', verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Pending review'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NEW', max_length=3, verbose_name='Membership request status'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='user',
            field=models.ForeignKey(help_text='User that requested membership in this organization', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membership applicant'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'Administrator'), (1, 'Staff')], default=1, verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organization member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='The actual date this project ended on.', null=True, verbose_name='Actual end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_start_date',
            field=models.DateField(blank=True, help_text='The actual date this project started on.', null=True, verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='available_data',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='available_staff',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='A descriptive image identifying the project, it can be a project logo, an image representing the problem you want to solve, etc.', null=True, verbose_name='Project main image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='List the main challenges that you foresee in the project implementation. Remember to frame them so volunteers understand that this is an exciting project.', max_length=5000, null=True, verbose_name='Main challenges'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deliverable_documentation_url',
            field=models.URLField(blank=True, help_text='Link to an external repository for project documentation - it will be listed in the final deliverables of the project when the project ends.', null=True, verbose_name='Documentation home'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deliverable_github_url',
            field=models.URLField(blank=True, help_text='Link to the home page of the project in Github - it will be listed in the final deliverables of the project when the project ends.', null=True, verbose_name='Project github home'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deliverable_management_url',
            field=models.URLField(blank=True, help_text="Link to an external home page for this project, probably under your organization's website - it will be listed in the final deliverables of the project when the project ends.", null=True, verbose_name='Project home page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deliverable_reports_url',
            field=models.URLField(blank=True, help_text='Link to an external repository of project reports - it will be listed in the final deliverables of the project when the project ends.', null=True, verbose_name='Project reports home'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer_agreement',
            field=models.TextField(blank=True, help_text='If you add an agreement, every volunteer that applies to the project will have to agree with those terms and conditions during their application process.', max_length=5000, null=True, verbose_name='Volunteer agreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intended_end_date',
            field=models.DateField(help_text='The planned end date of the project.', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intended_start_date',
            field=models.DateField(help_text='The planned start date of the project.', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='motivation',
            field=models.TextField(blank=True, help_text='Explain what is the context in which the project is needed, what is the motivation behind the project, and what are the goals of the project', max_length=5000, null=True, verbose_name='Context/motivation/goals'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of this project. Make sure it is distinctive and recognizable on its own.', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this project.', on_delete=django.db.models.deletion.CASCADE, to='marketplace.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_cause',
            field=models.CharField(choices=[('ED', 'Education'), ('HE', 'Health'), ('EN', 'Environment'), ('SS', 'Social Services'), ('TR', 'Transportation'), ('EE', 'Energy and Environment'), ('ID', 'International development'), ('PS', 'Public Safety'), ('EC', 'Economic Development'), ('OT', 'Other')], default='ED', help_text='The main social good cause this project is framed under. If there are several that apply, pick the most relevant one.', max_length=2, verbose_name='Social cause'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_impact',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='scoping_process',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_summary',
            field=models.TextField(help_text='Write a short description of the project that will be used as a summary of the project throughout the site.', max_length=1000, verbose_name='Short summary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution_description',
            field=models.TextField(blank=True, help_text='Describe what is the solution to the problem that will be build/created/deployed during this project.', max_length=5000, null=True, verbose_name='Proposed solution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('NW', 'New'), ('DE', 'In scoping phase'), ('DA', 'Waiting for design review'), ('WS', 'Waiting for volunteers'), ('IP', 'In progress'), ('WR', 'Waiting review'), ('CO', 'Completed'), ('EX', 'Expired'), ('RM', 'Deleted')], default='DR', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'Owner'), (1, 'Staff')], default=1, verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Project member'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='accepting_volunteers',
            field=models.BooleanField(help_text='Specify if volunteers can apply to this task at the moment or not.', verbose_name='Accepting volunteers?'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='actual_effort_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The actual number of hours that was spent in completing this task.', null=True, verbose_name='Actual effort (hours)'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='The actual date the work on this task finished on.', null=True, verbose_name='Actual end date'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='actual_start_date',
            field=models.DateField(blank=True, help_text='The actual date the work on this task started on.', null=True, verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='description',
            field=models.TextField(help_text='Describe in detail what the work for this task consists of, goals, methodologies, etc.', max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='estimated_effort_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Give your best estimate of how many hours need to be spent on this task to finish it.', null=True, verbose_name='Effort estimation (hours)'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='estimated_end_date',
            field=models.DateField(help_text='The planned end date for this specific task.', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='estimated_start_date',
            field=models.DateField(help_text='The planned start date for this specific task.', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification date'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='name',
            field=models.CharField(help_text='Descriptive name that identifies the task within the project.', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='onboarding_instructions',
            field=models.TextField(help_text='Explain in detail everything a volunteer needs to know to work on this task. They will receive these instructions immediately after being accepted to work on this task, so make sure to be specific enough for volunteers to be able to work in the task after reading these instructions.', max_length=5000, verbose_name='Volunteer onboarding instructions'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(help_text='The project this task belongs to.', on_delete=django.db.models.deletion.CASCADE, to='marketplace.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='stage',
            field=models.CharField(choices=[('NOT', 'Not started'), ('AVL', 'Accepting volunteers'), ('STA', 'Started'), ('PRW', 'Pending review'), ('COM', 'Completed'), ('DEL', 'Deleted')], default='NOT', max_length=3, verbose_name='Task status'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_deliverables_url',
            field=models.URLField(blank=True, help_text='Link to a repository (Github, Bitbucket, etc.) where the volunteers will put the results of their work.', null=True, verbose_name='External deliverables URL'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_home_url',
            field=models.URLField(blank=True, help_text='Link to an external home page for this task, that may contain additional documentation, data sets, etc.', null=True, verbose_name='External task home URL'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='type',
            field=models.CharField(choices=[('SCT', 'Project scoping'), ('PMT', 'Project management'), ('DWT', 'Domain work')], default='SCT', help_text='Different types of tasks have different roles within the project. Scoping tasks are needed to help new projects define the work that needs to be done. Project management tasks are used to guide the project from inception to finish. Domain work tasks include any data science work specified in the project.', max_length=3, verbose_name='Task type'),
        ),
        migrations.AlterField(
            model_name='projecttaskrequirement',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Nice to have'), (1, 'Important'), (2, 'Required')], default=0, help_text='Grade of criticality that this skill has for the task completion. Candidates with lower expertise levels or lacking a skill will be more suited if that skill is rated of low importance for the task.', verbose_name='Importance'),
        ),
        migrations.AlterField(
            model_name='projecttaskrequirement',
            name='level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Expert')], default=0, help_text='Minimum expertise level that the candidates should have in this skill to be suited for the task.', verbose_name='Required expertise level'),
        ),
        migrations.AlterField(
            model_name='projecttaskrequirement',
            name='skill',
            field=models.ForeignKey(help_text='Specific skill requirement.', on_delete=django.db.models.deletion.CASCADE, to='marketplace.Skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='projecttaskrequirement',
            name='task',
            field=models.ForeignKey(help_text='Project task this requirement applies to.', on_delete=django.db.models.deletion.CASCADE, to='marketplace.ProjectTask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='projecttaskreview',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='Date the review was completed on.', null=True, verbose_name='Review date'),
        ),
        migrations.AlterField(
            model_name='projecttaskreview',
            name='review_request_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the review request was created on by the volunter.', verbose_name='Request date'),
        ),
        migrations.AlterField(
            model_name='projecttaskreview',
            name='review_result',
            field=models.CharField(choices=[('NEW', 'Pending review'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NEW', help_text="Select if the task is accepted or rejected as completed (and specify why in the reviewer's comments).", max_length=3, verbose_name='Review result'),
        ),
        migrations.AlterField(
            model_name='projecttaskreview',
            name='reviewer_comment',
            field=models.TextField(blank=True, help_text='Add your feedback about the task. This is not private and will be shared with the volunteer.', max_length=2000, null=True, verbose_name="Reviewer's comments"),
        ),
        migrations.AlterField(
            model_name='projecttaskreview',
            name='task',
            field=models.ForeignKey(help_text='Project task this review is related to.', on_delete=django.db.models.deletion.CASCADE, to='marketplace.ProjectTask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='projecttaskreview',
            name='volunteer_comment',
            field=models.TextField(blank=True, help_text='Type any comment, feedback or insights that you have about the work you did', max_length=2000, null=True, verbose_name="Volunteer's comments"),
        ),
        migrations.AlterField(
            model_name='projecttaskreview',
            name='volunteer_effort_hours',
            field=models.PositiveSmallIntegerField(help_text='How many hours did you spend in this work?', verbose_name='Effort spent (in hours)'),
        ),
        migrations.AlterField(
            model_name='projecttaskrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'Volunteer')], default=0, verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='projecttaskrole',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.ProjectTask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='projecttaskrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Project task member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='initial_type',
            field=models.IntegerField(choices=[(0, 'Site staff'), (1, 'Volunteer'), (2, 'Organization member')], default=1, help_text='Users can check their preference when they sign up to indicate they want to be volunteers or create/join organizations', verbose_name='Initial type of user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Type your phone number in the format +999999999999999', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skype user name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_code',
            field=models.CharField(blank=True, help_text='Do you have a signup code from the person or organization that referred you to this site? These codes may unlock special features, so do not forget to use one if you have it.', max_length=20, null=True, verbose_name='Special signup code'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the volunteer applied on.', verbose_name='Application Date'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='private_reviewer_notes',
            field=models.TextField(blank=True, help_text='Private notes about the application. These notes will be shared with the rest of the project staff but not with the candidate or anybody else.', max_length=5000, null=True, verbose_name="Private reviewer's notes"),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='public_reviewer_comments',
            field=models.TextField(blank=True, help_text='Tell the candidate the reason of the acceptance or rejection, and any other comment you want to add. This is not private and will be shared with the volunteer. ', max_length=5000, null=True, verbose_name="Reviewer's comments"),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='resolution_date',
            field=models.DateTimeField(blank=True, help_text="The date the project staff accepted or rejected the volunteer's application.", null=True, verbose_name='Resolution date'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('NEW', 'Pending review'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NEW', help_text='Specifies whether this application is new or if it has been accepted or rejected.', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='task',
            field=models.ForeignKey(help_text='The project task this application is related to.', on_delete=django.db.models.deletion.CASCADE, to='marketplace.ProjectTask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.ForeignKey(help_text='The user applying to work on this task.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_application_letter',
            field=models.TextField(help_text='Introduce yourself and explain why you think you are the right candidate for working in this role.', max_length=5000, verbose_name='Application Letter'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='availability_end_date',
            field=models.DateField(blank=True, help_text="When is the latest date you are available for working on projects? Leave this field blank if you don't have restrictions on your availability.", null=True, verbose_name='Availability end date'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='availability_start_date',
            field=models.DateField(blank=True, help_text='When are you available to start working on projects? Leave this field blank if you can start at any time.', null=True, verbose_name='Availability start date'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Introduce yourself and tell projects and volunteers about your background and skills, your motivation for volunteering, your preferences for projects and work, what you want to acoomplish, and any other thing that you can think of.', max_length=2000, null=True, verbose_name='Cover letter'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='degree_level',
            field=models.IntegerField(choices=[(0, "Bachelor's"), (1, "Master's"), (2, 'PhD')], default=0, help_text='The level of the highest level degree you have.', verbose_name='Degree level'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='degree_name',
            field=models.CharField(blank=True, help_text='The name of the highest level degree you have. For example, Computer Science or Economics.', max_length=50, null=True, verbose_name='Degree name'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Add a link to your Github profile if you want to share code with potential projects so they can review your skills.', null=True, verbose_name='Github URL'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Add a link to your LinkedIn profile to show potential projects your professional background and experience.', null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Include any external site that has a showcase of your experience, skills, and/or background, and that projects may consider interesting or relevant to them', null=True, verbose_name='Portfolio URL'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='university',
            field=models.CharField(blank=True, help_text='The name of the institution (university, school, etc.) that issued the highest level degree you have.', max_length=50, null=True, verbose_name='Educational institution'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='user',
            field=models.OneToOneField(help_text='User this volunteer profile is attached to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='volunteer_status',
            field=models.CharField(choices=[('NEW', 'Pending review'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NEW', help_text='Describes if volunteers have been approved to apply to projects or if they still are pending approval.', max_length=3, verbose_name='Volunteer status'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='weekly_availability_hours',
            field=models.PositiveSmallIntegerField(help_text='Roughly, how many hours can you dedicate each week to volunteer work?', verbose_name='Weekly availability (hours)'),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Expert')], default=0, help_text='Type your phone number in the format +999999999999999', verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='skill',
            field=models.ForeignKey(help_text='Type your phone number in the format +999999999999999', on_delete=django.db.models.deletion.CASCADE, to='marketplace.Skill', verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='user',
            field=models.ForeignKey(help_text='Type your phone number in the format +999999999999999', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Phone number'),
        ),
    ]
