# Generated by Django 2.0.6 on 2018-06-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_organizationrole_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='target_url',
            field=models.URLField(blank=True, help_text='URL for the details of the notification.', null=True, verbose_name='Target URL'),
        ),
    ]
