# Generated by Django 2.0.6 on 2018-06-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_usernotification_target_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='target_url',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='target_id',
            field=models.IntegerField(blank=True, help_text='ID of the target entity that is related to this notification', null=True, verbose_name='Target ID'),
        ),
    ]
