# Generated by Django 2.0.6 on 2018-06-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20180623_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='stage',
            field=models.CharField(choices=[('NOT', 'Not started'), ('STA', 'Started'), ('PRW', 'Pending review'), ('COM', 'Completed'), ('DEL', 'Deleted')], default='NOT', max_length=3, verbose_name='Task status'),
        ),
    ]
