# Generated by Django 2.0.6 on 2018-06-29 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20180627_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='degree_level',
            field=models.IntegerField(blank=True, choices=[(0, "Bachelor's"), (1, "Master's"), (2, 'PhD')], default=0, help_text='The level of the highest level degree you have.', null=True, verbose_name='Degree level'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='weekly_availability_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Roughly, how many hours can you dedicate each week to volunteer work?', null=True, verbose_name='Weekly availability (hours)'),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Expert')], default=0, help_text='How proficient are you in this skill?', verbose_name='Skill level'),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
