# Generated by Django 2.0.6 on 2018-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20180705_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlog',
            name='change_target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='change_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='change_target',
            field=models.CharField(blank=True, choices=[('TK', 'Task'), ('VA', 'Volunteer application'), ('ST', 'Staff')], default='TK', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='change_type',
            field=models.CharField(blank=True, choices=[('AD', 'Added'), ('RM', 'Removed'), ('ED', 'Edited')], default='AD', max_length=2, null=True),
        ),
    ]
