# Generated by Django 2.0.6 on 2018-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_auto_20180710_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='severity',
            field=models.IntegerField(choices=[(0, 'info'), (1, 'warning'), (2, 'danger'), (3, 'primary')], default=0),
        ),
    ]
