# Generated by Django 2.0.6 on 2018-07-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_auto_20180712_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField(blank=True, help_text='The detailed scope of the project.', max_length=5000, null=True, verbose_name='Project scope')),
                ('version_notes', models.TextField(blank=True, help_text='Type the reason the scope is being modified and describe the changes made.', max_length=5000, null=True, verbose_name='Version notes')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('is_current', models.BooleanField(help_text='Specifies if this is the latest scope of the project.', verbose_name='Is current?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Project')),
            ],
        ),
    ]
