# Generated by Django 2.0.6 on 2018-07-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_auto_20180718_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_summary',
            field=models.TextField(default='', help_text='Write a short description of the organization that will be used throughout the site when needing a compact description.', max_length=1000, verbose_name='Short summary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='short_summary',
            field=models.TextField(default='', help_text='Write a short description of the task that will be used throughout the site when needing a compact description.', max_length=1000, verbose_name='Short summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='short_summary',
            field=models.TextField(help_text='Write a short description of the project that will be used throughout the site when needing a compact description.', max_length=1000, verbose_name='Short summary'),
        ),
    ]
