# Generated by Django 2.0.6 on 2018-07-18 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_auto_20180718_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='reviewer',
            field=models.ForeignKey(default=1, help_text='The user that did the review of this volunteer application.', on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_volunteer_application', to=settings.AUTH_USER_MODEL, verbose_name='Review author'),
            preserve_default=False,
        ),
    ]
