# Generated by Django 2.0.6 on 2018-07-19 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0035_auto_20180718_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SP', 'Fast work'), ('RS', 'Great reviews'), ('PC', 'Completed projects'), ('EU', 'Early user')], default='SP', max_length=2)),
                ('tier', models.IntegerField(choices=[(0, 'Tier 1: basic'), (1, 'Tier 2: advanced'), (2, 'Tier 3: master')], default=0, help_text='How advanced this reward is.', verbose_name='Badge tier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'type')},
        ),
    ]
