# Generated by Django 2.0.6 on 2018-07-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0039_auto_20180719_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deliverables_description',
            field=models.TextField(blank=True, help_text='Once the project is completed, the resulting deliverables will be presented in a separate page. This description will be placed at the top of the deliverables page, so you can describe if the goals of the project were met, how to interpret the results, where the different artifacts of the project are stored, etc.', max_length=5000, null=True, verbose_name='Deliverables page description'),
        ),
    ]
