# Generated by Django 2.0.6 on 2018-07-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_project_deliverables_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='ahead_of_time_task_ratio',
            field=models.FloatField(blank=True, help_text='Ratio of the tasks that the user completed ahead of the estimated time.', null=True, verbose_name='Ratio of tasks ahead of time'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='average_review_score',
            field=models.FloatField(blank=True, help_text='Average review score', null=True, verbose_name='Average review score'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='completed_task_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of task this user has completed', null=True, verbose_name='Completed task count'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='source',
            field=models.CharField(choices=[('GN', 'Generic'), ('OR', 'Organization'), ('PJ', 'Project'), ('TK', 'Task'), ('VA', 'Volunteer application'), ('OM', 'Organization membership request'), ('BA', 'Award')], default='GN', max_length=2),
        ),
    ]
