# Generated by Django 2.0.6 on 2018-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_auto_20180721_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_edited',
            field=models.BooleanField(default=True, help_text='Specifies if the user has edited the profile or if it has the default initial settings.', verbose_name='Is edited?'),
            preserve_default=False,
        ),
    ]
