# Generated by Django 2.0.6 on 2018-07-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0047_auto_20180722_2039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttaskrole',
            unique_together={('user', 'task', 'role')},
        ),
    ]
