# Generated by Django 2.0.6 on 2018-07-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0049_signupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcode',
            name='current_uses',
            field=models.IntegerField(blank=True, default=0, help_text='Number of times this code has been used.', null=True, verbose_name='Times used'),
        ),
    ]
