# Generated by Django 2.0.6 on 2018-07-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0054_auto_20180724_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Upload an image file that represents your organization', null=True, upload_to='', verbose_name='Organization logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL of an external image file that represents your organization', null=True, verbose_name='Organization logo URL'),
        ),
    ]
