# Generated by Django 2.0.6 on 2018-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0055_auto_20180724_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Upload an image file that represents your organization', null=True, upload_to='orglogos/', verbose_name='Organization logo'),
        ),
    ]
