# Generated by Django 2.0.6 on 2018-07-24 16:48

from django.db import migrations, models
import marketplace.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0057_auto_20180724_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image_file',
            field=models.ImageField(blank=True, help_text='A descriptive image identifying the project, it can be a project logo, an image representing the problem you want to solve, etc.', null=True, upload_to='projlogos/', validators=[marketplace.models.common.validate_image_size], verbose_name='Project main image'),
        ),
    ]
