# Generated by Django 2.0.6 on 2018-07-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0059_user_profile_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcode',
            name='type',
            field=models.IntegerField(choices=[(0, 'Automatically accept user as volunteer'), (1, 'Automatically make users DSSG staff members so they can review volunteer applications')], default=0),
        ),
    ]
