# Generated by Django 2.0.6 on 2018-07-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0061_auto_20180727_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Specifies if this is a demonstration organization', verbose_name='Demo organization?'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Specifies if this is a demonstration project', verbose_name='Demo project?'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='stage',
            field=models.CharField(choices=[('DRF', 'Draft'), ('NOT', 'Not started'), ('STA', 'Started'), ('PRW', 'Pending review'), ('COM', 'Completed'), ('DEL', 'Deleted')], default='NOT', max_length=3, verbose_name='Task status'),
        ),
    ]
