# Generated by Django 2.0.6 on 2018-08-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0065_newspiece_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspiece',
            name='contents',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='News contents'),
        ),
        migrations.AlterField(
            model_name='newspiece',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
