# Generated by Django 2.0.6 on 2018-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0068_auto_20180815_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='available_staff',
            field=models.TextField(blank=True, help_text="List the organization's staff that can be available throughout the project to support the volunteers and ensure the project gets completed successfully.", max_length=5000, null=True, verbose_name='Internal people available during the project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='motivation',
            field=models.TextField(blank=True, help_text='Explain what is the context in which the project is needed and what is the motivation behind the project.', max_length=5000, null=True, verbose_name='Background and motivation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_analysis',
            field=models.TextField(blank=True, help_text='What analysis needs to be done on the available data to achieve the stated goals?', max_length=5000, null=True, verbose_name='Scope: analysis needed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_goals',
            field=models.TextField(blank=True, help_text='Describe the goals and subgoals that the success of the project will be measured against.', max_length=5000, null=True, verbose_name='Scope: project goal(s)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_implementation',
            field=models.TextField(blank=True, help_text='What is the implementation plan after the project is finished? How will it be used by the end users? What is the time frame for production deployment?', max_length=5000, null=True, verbose_name='Scope: implementation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_interventions',
            field=models.TextField(blank=True, help_text='List the interventions and actions that are available for this project.', max_length=5000, null=True, verbose_name='Scope: interventions and actions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_validation_methodology',
            field=models.TextField(blank=True, help_text='Describe the validation methodology or methodologies that will be used to measure the success of the project.', max_length=5000, null=True, verbose_name='Scope: validation methodology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution_description',
            field=models.TextField(blank=True, help_text='Give a general description of the project.', max_length=5000, null=True, verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stakeholders',
            field=models.TextField(blank=True, help_text='List the main stakeholders of the project within your organization.', max_length=5000, null=True, verbose_name='Internal stakeholders'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='scope_analysis',
            field=models.TextField(blank=True, help_text='What analysis needs to be done on the available data to achieve the stated goals?', max_length=5000, null=True, verbose_name='Analysis needed'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='scope_goals',
            field=models.TextField(blank=True, help_text='Describe the goals and subgoals that the success of the project will be measured against.', max_length=5000, null=True, verbose_name='Project goal(s)'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='scope_implementation',
            field=models.TextField(blank=True, help_text='What is the implementation plan after the project is finished? How will it be used by the end users? What is the time frame for production deployment?', max_length=5000, null=True, verbose_name='Implementation'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='scope_interventions',
            field=models.TextField(blank=True, help_text='List the interventions and actions that are available for this project.', max_length=5000, null=True, verbose_name='Interventions and actions'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='scope_validation_methodology',
            field=models.TextField(blank=True, help_text='Describe the validation methodology or methodologies that will be used to measure the success of the project.', max_length=5000, null=True, verbose_name='Validation methodology'),
        ),
    ]
