# Generated by Django 2.0.6 on 2018-08-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0069_auto_20180815_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Phone number (Optional)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skype user name (Optional)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_code',
            field=models.CharField(blank=True, help_text='Do you have a signup code from the person or organization that referred you to this site? These codes may unlock special features, so do not forget to use one if you have it.', max_length=20, null=True, verbose_name='Special signup code (Optional)'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Add a link to your Github profile to help us review your programming skills.', null=True, verbose_name='Github URL'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Add a link to your LinkedIn profile to show potential projects or your professional background and experience.', null=True, verbose_name='LinkedIn URL'),
        ),
    ]
