# Generated by Django 2.0.6 on 2018-10-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0070_auto_20180826_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSocialCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_cause', models.CharField(choices=[('ED', 'Education'), ('HE', 'Health'), ('EN', 'Environment'), ('SS', 'Social Services'), ('TR', 'Transportation'), ('EE', 'Energy and Environment'), ('ID', 'International development'), ('PS', 'Public Safety'), ('EC', 'Economic Development'), ('OT', 'Other')], default='ED', help_text='What is the social cause that this organization has as a goal?', max_length=2, verbose_name='Social cause')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Organization', verbose_name='Organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='organizationsocialcause',
            unique_together={('social_cause', 'organization')},
        ),
    ]
