# Generated by Django 2.0.6 on 2018-10-02 20:33
from django.db import migrations


MODEL_NAMES = (
    'newspiece',
    'organization',
    'organizationmembershiprequest',
    'organizationrole',
    'pinnedtaskreview',
    'project',
    'projectcomment',
    'projectdiscussionchannel',
    'projectfollower',
    'projectlog',
    'projectrole',
    'projectscope',
    'projecttask',
    'projecttaskrequirement',
    'projecttaskreview',
    'projecttaskrole',
    'signupcode',
    'skill',
    'user',
    'userbadge',
    'usernotification',
    'volunteerapplication',
    'volunteerprofile',
    'volunteerskill',
)

TABLE_NAMES = (
    'marketplace_newspiece',
    'marketplace_organization',
    'marketplace_organizationmembershiprequest',
    'marketplace_organizationrole',
    'marketplace_pinnedtaskreview',
    'marketplace_project',
    'marketplace_projectcomment',
    'marketplace_projectdiscussionchannel',
    'marketplace_projectfollower',
    'marketplace_projectlog',
    'marketplace_projectrole',
    'marketplace_projectscope',
    'marketplace_projecttask',
    'marketplace_projecttaskrequirement',
    'marketplace_projecttaskreview',
    'marketplace_projecttaskrole',
    'marketplace_signupcode',
    'marketplace_skill',
    'marketplace_user',
    'marketplace_userbadge',
    'marketplace_usernotification',
    'marketplace_volunteerapplication',
    'marketplace_volunteerprofile',
    'marketplace_volunteerskill',
)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        # ('dssgmkt', '0074_auto_20181002_1650'),
        ('marketplace', '0074_auto_20181002_1650'),
    ]

    #
    # The below was used to generate the table renaming SQL in 0071_custom.sql.
    #
    # It is left here, commented out, as a record, for reproduction, and as a
    # spacer for the 0071 sql file.
    #
    operations = [
        # migrations.AlterModelTable(model_name, table_name)
        # for (model_name, table_name) in zip(MODEL_NAMES, TABLE_NAMES)
    ]
