# Generated by Django 2.0.9 on 2018-10-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0076_auto_20181002_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='type',
            field=models.CharField(choices=[('SCT', 'Project scoping'), ('PMT', 'Project management'), ('DWT', 'Data science'), ('QAT', 'QA')], default='SCT', help_text='Different types of tasks have different roles within the project. Scoping tasks are needed to help new projects define the work that needs to be done. Project management tasks are used to guide the project from inception to finish. Domain work tasks include any data science work specified in the project.', max_length=3, verbose_name='Task type'),
        ),
        migrations.AlterField(
            model_name='usertaskpreference',
            name='preference',
            field=models.CharField(choices=[('SCT', 'Project scoping'), ('PMT', 'Project management'), ('DWT', 'Data science'), ('QAT', 'QA')], default='SCT', help_text='Choose what type of tasks you are interested in working in.', max_length=3, verbose_name='Task type'),
        ),
    ]
