# Generated by Django 2.0.9 on 2018-10-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0077_auto_20181005_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('SGP', 'Social good organization'), ('VOL', 'Volunteer group')], default='SGP', max_length=3, verbose_name='Organization type'),
        ),
    ]
