# Generated by Django 2.0.9 on 2018-10-25 19:22

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0079_auto_20181010_1536'),
    ]

    operations = [
        CITextExtension(),

        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already in use.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
