# Generated by Django 2.2.1 on 2020-08-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0080_auto_20181025_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_description',
            field=models.TextField(),
        ),
    ]
