#!/usr/bin/env bash
#
# install-cli
#
# Copy this file into your project to enable easy, guided
# installation/bootstrapping.
#
# Don't like sh/bash/etc? Sure.
#
# Love sh/bash/etc? Yeah, but....
#
# Let's use it here, to bootstrap whatever tools/libraries/etc. we
# *really* love for our project.
#
# You can name your implementation of this script whatever you like,
# such as: install
#

# Update INSTALL_VERSION to require the version of install-cli this
# script expects
INSTALL_VERSION=0.0.4

#
# start bootstrap installation lib
#
# This is a *bit* of boilerplate to ensure we've downloaded the correct
# version of install-cli. (You probably don't need to touch this.)
#

INSTALL_FILE=.install.${INSTALL_VERSION//./-}.bash.inc

INSTALL_URL=https://raw.githubusercontent.com/dssg/install-cli/$INSTALL_VERSION/install.bash.inc

[ -f $INSTALL_FILE ] || curl -#L $INSTALL_URL -o $INSTALL_FILE

. $INSTALL_FILE

#
# end bootstrap installation lib
#

#
# start project check/install
#

# pyenv

pyenv_bin="${PYENV_ROOT:-$HOME/.pyenv}/bin"

exists_pyenv() {
  [ -d "$pyenv_bin" ]
}

boostrap_pyenv() {
  export PATH="$pyenv_bin:$PATH"

  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
}

install_pyenv() {
  curl -#L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

  boostrap_pyenv  # bootstrap for subsequent commands
}

require pyenv \
  exists_pyenv \
  install_pyenv \
  --fail-prefix="not found"

if exists_pyenv
then
  echo
  icli::set_context pyenv

  if icli::check_command pyenv
  then
    icli::message "${T_FGREEN}initialized ✓"
  else
    icli::message "${T_FRED}not set up ✗"
    icli::message
    icli::message "${T_FYELLOW}hint: add the following lines to your .bashrc, .bash_profile or .zshenv, $(tput sitm)etc."
    icli::message
    icli::message '\texport PATH="~/.pyenv/bin:$PATH"'
    icli::message '\teval "$(pyenv init -)"'
    icli::message '\teval "$(pyenv virtualenv-init -)"'
    icli::message
    icli::message "${T_FMAGENTA}reference: https://github.com/pyenv/pyenv"
    icli::message "${T_FMAGENTA}reference: https://github.com/pyenv/pyenv-installer/"

    boostrap_pyenv  # bootstrap for subsequent commands
  fi

  icli::unset_context
fi

# python

PY_VERSION=3.7.0

which_python() {
  local py_version="$1"

  local installed_info
  local python_exe="python${py_version}"

  while true; do
    if icli::check_command $python_exe || [ $python_exe = python ]; then
      break
    else
      # strip a version part from the exe
      # NOTE: must support POSIX sed (not just GNU)
      python_exe="$(<<<"$python_exe" sed -Ee 's/\.{0,1}[0-9]{1,}$//')"
    fi
  done

  installed_info="$($python_exe --version 2>/dev/null)"
  if icli::check_command $python_exe && [ -z "$installed_info" ]; then
    # python <3.4 printed version to stderr
    installed_info="$($python_exe --version 2>&1)"
  fi

  if [ "${installed_info#* }" = "$py_version" ]; then
    echo $python_exe
    return 0
  else
    return 1
  fi
}

exists_python() {
  if icli::check_command pyenv; then
    pyenv versions 2> /dev/null | grep -E "^ *${PY_VERSION}$" > /dev/null
  else
    # check if installed globally or via an active virtual environment
    which_python $PY_VERSION > /dev/null
  fi
}

install_python() {
  pyenv install -s $PY_VERSION
}

require "python-${PY_VERSION}" \
  exists_python \
  install_python \
  --fail-prefix="v${PY_VERSION} not found"

# virtualenv

PROJECT=$(<.python-version)

exists_virtualenv() {
  test "$(pyenv version-name 2> /dev/null)" == "$PROJECT"
}

install_virtualenv() {
  pyenv virtualenv $PY_VERSION $PROJECT
}

if icli::check_command pyenv
then
  require virtualenv \
    exists_virtualenv \
    install_virtualenv \
    --fail-prefix="pyenv project virtual environment \"$PROJECT\" not found"
else
  echo
  icli::set_context virtualenv
  icli::message "${T_FYELLOW}pyenv required – will not install ✗"
  icli::unset_context
fi

# python libs

install_lib() {
  pip install -r requirement/console.txt
}

# no great way to check that python libs installed;
# rather, always fail check and let pip figure it out
require lib \
  icli::always_install \
  install_lib

# ecs-cli

ECSCLI_PATH=~/.local/bin/ecs

ECSCLI_URL=https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
ECSCLI_MD5="$ECSCLI_URL.md5"

exists_ecscli() {
  [ -f $ECSCLI_PATH ]
}

install_ecscli() {
  mkdir -p $(dirname $ECSCLI_PATH)
  curl -#L -o $ECSCLI_PATH $ECSCLI_URL
  echo "$(curl -s $ECSCLI_MD5) $ECSCLI_PATH" | md5sum -c -
}

require ecs-cli \
  exists_ecscli \
  install_ecscli \
  --fail-prefix="not found ($ECSCLI_PATH)"

[ -x $ECSCLI_PATH ] || chmod u+x $ECSCLI_PATH

icli::set_context ecs-cli
icli::check_command ecs || icli::message "${T_FRED}ensure that $(dirname $ECSCLI_PATH) is on your PATH"
icli::unset_context

# env

icli::set_context env

if [ ! -e .env ]
then
  SECRET_KEY=$(python - <<<"
import random
import string
sys_random = random.SystemRandom()
allowed = string.ascii_lowercase + string.digits + '!@#$%^&*(-_=+)'
chars = (sys_random.choice(allowed) for _i in range(50))
print(*chars, sep='')
")
  sed "s/^SECRET_KEY=$/\0$SECRET_KEY/" .env.example > .env

  echo
  icli::message "${T_FYELLOW}customize .env as needed"
fi

icli::unset_context

# # environment variables
#
# EXPECTED_ENVVARS="PGHOST PGPORT PGUSER PGDATABASE"
#
# check_envvars() {
#   icli::check_envvars $EXPECTED_ENVVARS
# }
#
# require envvars \
#   check_envvars \
#   --fail-prefix="one or more of these environment variables missing ($EXPECTED_ENVVARS)"

#
# end project check/install
#
