# Generated by Django 2.0.6 on 2018-06-04 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('notification_description', models.CharField(max_length=500)),
                ('is_read', models.BooleanField()),
                ('severity', models.IntegerField(choices=[(0, 'Information'), (1, 'Warning'), (2, 'Alert')], default=0)),
                ('source', models.CharField(choices=[('GN', 'Generic'), ('OR', 'Organization'), ('PJ', 'Project'), ('TK', 'Task'), ('VA', 'Volunteer application'), ('OM', 'Organization membership request')], default='GN', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='VolunteerDetails',
            new_name='VolunteerProfile',
        ),
    ]
