# Generated by Django 2.0.6 on 2018-06-24 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0010_auto_20180623_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time in which the organization role was created', verbose_name='Creation date'),
            preserve_default=False,
        ),
    ]
