# Generated by Django 2.0.6 on 2018-07-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0022_auto_20180710_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='change_target',
            field=models.CharField(blank=True, choices=[('TK', 'Task'), ('VA', 'Volunteer application'), ('ST', 'Staff'), ('TK', 'Task review'), ('VO', 'Volunteer')], default='TK', max_length=2, null=True),
        ),
    ]
