# Generated by Django 2.0.6 on 2018-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0025_auto_20180712_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='change_target',
            field=models.CharField(blank=True, choices=[('TK', 'Task'), ('VA', 'Volunteer application'), ('ST', 'Staff'), ('TK', 'Task review'), ('VO', 'Volunteer'), ('SU', 'Status'), ('IN', 'Information')], default='TK', max_length=2, null=True),
        ),
    ]
