# Generated by Django 2.0.6 on 2018-07-19 19:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0036_auto_20180719_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_summary',
            field=markdownx.models.MarkdownxField(help_text='Write a short description of the project that will be used throughout the site when needing a compact description.', max_length=1000, verbose_name='Short summary'),
        ),
    ]
