# Generated by Django 2.0.6 on 2018-07-19 19:50

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0037_auto_20180719_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='available_data',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Describe the data available to use for this project. (Size, variables, completeness, availability, privacy, etc.)', max_length=5000, null=True, verbose_name='Available data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='available_staff',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Who from your organization would be available to provide assistance (approximately 1-3 hours per week) throughout the summer? (Technical staff, subject matter experts, etc.)', max_length=5000, null=True, verbose_name='Available staff'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=markdownx.models.MarkdownxField(blank=True, help_text='List the main challenges that you foresee in the project implementation. Remember to frame them so volunteers understand that this is an exciting project.', max_length=5000, null=True, verbose_name='Main challenges'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer_agreement',
            field=markdownx.models.MarkdownxField(blank=True, help_text='If you add an agreement, every volunteer that applies to the project will have to agree with those terms and conditions during their application process.', max_length=5000, null=True, verbose_name='Volunteer agreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='motivation',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Explain what is the context in which the project is needed, what is the motivation behind the project, and what are the goals of the project', max_length=5000, null=True, verbose_name='Context/motivation/goals'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_impact',
            field=markdownx.models.MarkdownxField(blank=True, help_text="How critical is this project for your organization? How you're solving this problem today? What's the impact if this project is completed successfully?", max_length=5000, null=True, verbose_name='Project impact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scoping_process',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Describe the internal process for scoping and implementing this project (Who are the stakeholders, what discussions have already happened, etc.)', max_length=5000, null=True, verbose_name='Scoping process'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_summary',
            field=models.TextField(help_text='Write a short description of the project that will be used throughout the site when needing a compact description.', max_length=1000, verbose_name='Short summary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Describe what is the solution to the problem that will be build/created/deployed during this project.', max_length=5000, null=True, verbose_name='Proposed solution'),
        ),
    ]
