# Generated by Django 2.0.6 on 2018-07-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0042_pinnedtaskreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pinnedtaskreview',
            unique_together={('task_review', 'user')},
        ),
    ]
