# Generated by Django 2.0.6 on 2018-07-22 15:41

from django.db import migrations, models
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0044_volunteerprofile_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
