# Generated by Django 2.0.6 on 2018-07-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0046_auto_20180722_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttaskrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'Volunteer'), (1, 'Staff')], default=0, verbose_name='User role'),
        ),
    ]
