# Generated by Django 2.0.6 on 2018-07-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0051_auto_20180723_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdiscussionchannel',
            name='related_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dssgmkt.ProjectTask'),
        ),
    ]
