# Generated by Django 2.0.6 on 2018-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0064_newspiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspiece',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='External URL'),
        ),
    ]
