# Generated by Django 2.0.6 on 2018-10-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dssgmkt', '0071_auto_20181001_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSocialCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_cause', models.CharField(choices=[('ED', 'Education'), ('HE', 'Health'), ('EN', 'Environment'), ('SS', 'Social Services'), ('TR', 'Transportation'), ('EE', 'Energy and Environment'), ('ID', 'International development'), ('PS', 'Public Safety'), ('EC', 'Economic Development'), ('OT', 'Other')], default='ED', help_text='What is the social cause that this project has as a goal?', max_length=2, verbose_name='Social cause')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dssgmkt.Project', verbose_name='Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectsocialcause',
            unique_together={('social_cause', 'project')},
        ),
    ]
